version: '3.1'
services:
    test:
        image: 'alpine'
        command: 'cat /run/secrets/my_secret '
        secrets: 
            - my_secret

secrets:
    my_secret:
        file: ./mysecret.txt

