version: '3.1'
services:
    test:
        image: 'alpine'
        command: 'cat /run/secrets/manual_secret '
        secrets: 
            - manual_secret

secrets:
    manual_secret:
        external: true

